[project]
name = "auth-service"
version = "0.1.0"
description = "Authentication Service for Order Processing System"
dependencies = [
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
    "sqlmodel>=0.0.14",
    "psycopg2-binary>=2.9.9",
    "python-jose[cryptography]>=3.3.0",
    "bcrypt>=4.0.0",
    "python-dotenv>=1.0.1",
    "pydantic-settings>=2.1.0",
    "python-multipart>=0.0.7",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-logging"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
