from fastapi import FastAPI, HTTPException
from typing import List
from pydantic import BaseModel
import grpc
import sys
import os

# Import generated gRPC code
# Note: In a real scenario, these would be generated by protoc
# from proto.order.v1 import order_pb2, order_pb2_grpc

app = FastAPI(title="Order Processing API Gateway")

class OrderItem(BaseModel):
    product_id: str
    quantity: int
    price: float

class CreateOrderRequest(BaseModel):
    customer_id: str
    items: List[OrderItem]

@app.get("/")
async def root():
    return {"message": "Welcome to Order Processing API Gateway"}

@app.post("/orders")
async def create_order(request: CreateOrderRequest):
    # This will eventually call the Go Order Service via gRPC
    return {"message": "Order creation initiated (Mock)", "customer_id": request.customer_id}

@app.get("/orders/{order_id}")
async def get_order(order_id: str):
    return {"order_id": order_id, "status": "PENDING (Mock)"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
