[project]
name = "api-gateway"
version = "0.1.0"
description = "Order Processing API Gateway"
authors = [
    {name = "Your Name", email = "you@example.com"}
]
dependencies = [
    "fastapi[standard]",
    "grpcio",
    "grpcio-tools",
    "pydantic",
    "python-jose[cryptography]",
    "python-dotenv",
    "python-multipart>=0.0.7"
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
