
services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./order-service:/app
    ports:
      - "50051:50051"
    environment:
      - INVENTORY_SERVICE_ADDR=inventory-service:50052
    # Overriding CMD to use air for hot-reloading
    command: sh -c "go install github.com/air-verse/air@latest && air -c .air.toml"
    networks:
      - grpc-net
    depends_on:
      - inventory-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway/src:/app/src
    environment:
      - ORDER_SERVICE_ADDR=order-service:50051
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - order-service
    networks:
      - grpc-net

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    volumes:
      - ./inventory-service/src:/app/src
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # Use uvicorn with reload for the FastAPI part, gRPC will restart when uvicorn reloads the module
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - grpc-net


  web-client:
    build:
      context: ./web-client
    volumes:
      - ./web-client:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - api-gateway
      - inventory-service
    networks:
      - grpc-net

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - web-client
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge

volumes:
  inventory-data:
