
services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "50051:50051"
    environment:
      - INVENTORY_SERVICE_ADDR=inventory-service:50052
      - DATABASE_URL=${ORDER_DATABASE_URL}
    networks:
      - grpc-net
    depends_on:
      - inventory-service
      - kafka

  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - ORDER_SERVICE_ADDR=order-service:50051
      - STREAM_SERVICE_ADDR=order-streamer:50053
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-key}
    depends_on:
      - order-service
      - order-streamer
      - auth-service
    networks:
      - grpc-net

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${ORDER_DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-key}
    depends_on:
      - kafka
    networks:
      - grpc-net

  inventory-service:
    build:
      context: ./inventory-service
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - grpc-net

  order-streamer:
    build:
      context: ./order-streamer
    environment:
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - grpc-net

  web-client:
    build:
      context: ./web-client
    depends_on:
      - api-gateway
      - inventory-service
    networks:
      - grpc-net

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - web-client
    networks:
      - grpc-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - grpc-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge

volumes:
  inventory-data:
